# Site settings
title: 夏城 Blog
SEOTitle: 夏城 Blog
header-img: img/post-bg-desk.jpg
email: zhanxiachengzxc@sina.com
description: "Live as if you were to die tomorrow. Learn as if you were to live forever."
keyword: "ShadowZxc, 夏城 Blog, web, 后台, "
url: "https://ShadowZxc.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/ShadowZxc/ShadowZxc.github.io" # you code repository
logo: /img/logo-64.png
recordNum: 备案号暂无 #粤ICP备18042434号-1 # 备案号

# Sidebar settings
sidebar: false                           # whether or not using Sidebar.
sidebar-about-description: "When the night is darkest, dawn is nearest!"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     shadowzxc
#zhihu_username:     shadowzxc
github_username:    shadowzxc
#facebook_username:  shadowzxc
#jianshu_username:   shadowzxc
#twitter_username:   shadowzxc




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: shadowzxc

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: dcb71993184db7731eed                            #生成的clientID
  clientSecret: 919247b52c3bfca6190a951751ad8c51971edee5    #生成的clientSecret
  repo: ShadowZxc.github.io    #仓库名称 -> 存储你评论 issue 的 Github 仓库名
  owner: ShadowZxc    #github用户名
  admin: ShadowZxc
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 来必力
# livere_uid: MTAyMC80NDEzNy8yMDY3Mg==

# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: ''

# Google Analytics
# ga_track_id: 'UA-139898215-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [{
        title: "Apple",
        href: "https://apple.com"
    }
]
